labelstudio_file: "./data/information_extraction/label_studio_data/label_studio_output.json"
save_dir: "./data/information_extraction/model_input_data/"
seed: 1000
split_ratio: [0.8, 0.1, 0.1]
is_shuffle: True
is_regularize_data: True
