data_args:
    data_file: "./data/information_extraction/model_infer_data/example_for_txt_type_data.txt"
    save_dir: "./reports/information_extraction/inference_results/"
    save_name: "inference_results.txt"
    is_regularize_data: False
    text_list: null

taskflow_args:
    device_id: 0
    precision: "fp32"
    batch_size: 1
    model: "uie-base"
    task_path: "./models/information_extraction/checkpoint/model_best"

strategy_args:
    select_strategy: "threshold"
    select_strategy_threshold: 0.5
    select_key: ["text", "start", "end", "probability"]
