data_args:
    data_file: "./data/information_extraction/model_infer_data/example_for_json_type_data.json"
    data_type: "json_type"
    save_dir: "./reports/information_extraction/inference_results/"
    save_name: "inference_results.json"
    is_regularize_data: True
    text_list: null

taskflow_args:
    device_id: -1
    precision: "fpew"
    batch_size: 1
    model: "uie-base"
    task_path: null
    #task_path: "../Chinese-Verdict-NLP/results/checkpoint/model_best"
    #task_path: "./models/information_extraction/checkpoint/model_best"

strategy_args:
    select_strategy: "all"
    select_strategy_threshold: 0.5
    select_key: ["text", "start", "end", "probability"]
